import './globals.css'
import type { Metadata } from 'next'

import StyledComponentsRegistry from './lib/Registry'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'NextPlayer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <h1>
          <Link href="/pages/signup">넥스트 플레이어 회원가입</Link>
        </h1>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  )
}
